### ISSUE TITLE
Way to run multiple puppeteer browser instances

### ISSUE THREAD

**Issue by weiljoe** [TrevorSundberg/puppeteer-in-electron#6]
Isn't it possible to run multiple sessions of puppeteer browsers?
I'd like to run several puppeteer instances inside several ElectronJs browsers.
But electron only allows one remote-debugging-port
Is there a workaround?

**Comment by TrevorSundberg** [comment]
You should be able to call `pie.connect` more than once, the port they host on is just a listening port (they can accept multiple connections on it). Let me test this to be sure it's possible.

**Comment by TrevorSundberg** [comment]
Great find, and I think there's a pretty simple fix where we just run the login for picking the port once.

**Comment by weiljoe** [comment]
👍

**Comment by TrevorSundberg** [comment]
@weiljoe I pushed two versions:
### 1.0.9
Fixes this by using a fixed port instead of a random port (may bite me in the future but I'm done trying to solve the port problem, since we already had an issue on machine's that didn't have `netstat`). One thing to note is that `pie.connect` must be called before the electron app is ready because it modifies the command line arguments. That just means you need to once before, but after that you can call it as many times as you want.

### 2.0.0
This version added a new `initialize` function that must be called before the application is ready. I separated out `initialize` from `connect`, so now `connect` does not take the port, and can be called as many times as you want (any time after `initialize` has been called, even after the electron app is ready).
