### ISSUE TITLE
Error while accessing page in Multi Instance app (NOT multi window)

### ISSUE THREAD

**Issue by cstayyab** [TrevorSundberg/puppeteer-in-electron#9]
When multiple instance of an electron app are open then only first instance is connected to puppeteer. In second instance when `pie.getPage` is called it raises following exception:
```
Error: Unable to find puppeteer Page from BrowserWindow. Please report this.
    at Object.exports.getPage (/home/user/Development/WALC/node_modules/puppeteer-in-electron/bin/index.js:93:15)
```
I am using the latest version (2.0.4) of `puppeteer-in-electron`

**Comment by cstayyab** [comment]
I don't know the reason but passing it a separate port to `pie.initialize(app, freePort)` in each instance solves the issue. Here is the code that solved the issue:

```javascript
const getPortSync = require('get-port-sync');
let freePort = null;
try {
    freePort = getPortSync()
    pie.initialize(app, freePort)
}
catch (e) { console.log(e) }
```

You might wanna integrate this solution to the library. I am sending a PR in hope that you would definitely wanna integrate it.

**Comment by TrevorSundberg** [comment]
I hadn't thought of the issue of running multiple (which to me is now very obvious when you're running a test suite). This problem has plagued me. It has to be sync because electron only parses command line arguments until the ready callback is invoked and there's no way that I know to delay it. You're solution is correct, however it's actually already what I was doing in a past version:

See this pull request:

https://github.com/TrevorSundberg/puppeteer-in-electron/pull/3

Originally I used deasync with getPort, but on some versions of electron this would segfault.
https://github.com/TrevorSundberg/puppeteer-in-electron/blob/0d242578f1ed595ad2d604baea0dd05681bf2eeb/index.ts#L31

It turns out its because deasync AFAIK actually links in native code that is not compatible with some versions of electron on some platforms, causing the crash. 

https://stackoverflow.com/questions/49198704/npm-deasync-cause-crash-in-electron
https://github.com/abbr/deasync/issues/95

I personally ran into this crash myself and was quite confused until I narrowed it down to deasync.

Another pretty kludgy way of running synchronous code is to run a separate process synchronously. So I have a version that did that but another user ran into problems where it broke his webpack code and did not work in packaged deployments. Another third option was to synchronously shell out to `netstat` as it exists on all platforms... or so I thought. That was the most recent thing we changed was to a library that did exactly that (you can see in that same PR above). However `netstat` is not universal, for example a fresh install of Ubuntu 19.10 does not include it by default.

I'm open to ideas, but I can't merge the PR :(

**Comment by TrevorSundberg** [comment]
Ok I pushed **3.0.0**. I finally just accepted the race exists, and I'm going to upstream it as a bug to electron. From testing the race only hits if it can't find a port for a few seconds, so I'm not particularly worried about it ever happening in a production environment, but it does exist. Electron needs a way to delay starting so that an async function can pass command line arguments.
